### ISSUE TITLE
eslintrc package not found

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-js#19]
## Bug Summary

When attempting to install dependencies, I receive the following error:
```
error An unexpected error occurred: "https://registry.yarnpkg.com/@amaurymartiny/eslintrc/-/eslintrc-1.3.3.tgz: Request failed \"404 Not Found\"".
```

## Potential Solutions

(1) Remove dependency and add custom eslintrc configuration
(2) Add eslintrc package to regen-network organization and update dependency

**Comment by amaurym** [comment]
Oops, i renamed my Github and npm logins at some point to @amaurym, but forgot to update it here.

I initially used my personal eslintrc config because when I started hacking on this, this was still a PoC. We should move away from my personal config for sure.

It makes sense to use a shared eslint config with regen-web, imo we can start with (1) here by copy-pasting that eslintrc, and later decide with the web team where to host Regen's (hopefully unique) eslint config.
